package com.example.agrimanager.utils

import android.content.Context
import android.os.Environment
import com.example.agrimanager.data.models.ExportData
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.*
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class PdfExportManager @Inject constructor(
    @ApplicationContext private val context: Context
) {
    
    private val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale.getDefault())
    private val dateTimeFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
    
    fun generatePdf(data: ExportData): Result<File> {
        return try {
            val fileName = "AgriManager_Report_${System.currentTimeMillis()}.pdf"
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            
            // Create downloads directory if it doesn't exist
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            
            val file = File(downloadsDir, fileName)
            
            val pdfWriter = PdfWriter(file)
            val pdfDocument = PdfDocument(pdfWriter)
            val document = Document(pdfDocument)
            
            // Add content
            addHeader(document, data)
            
            data.machines?.let { if (it.isNotEmpty()) addMachinesSection(document, it) }
            data.fuelLogs?.let { if (it.isNotEmpty()) addFuelLogsSection(document, it) }
            data.employees?.let { if (it.isNotEmpty()) addEmployeesSection(document, it) }
            data.transactions?.let { if (it.isNotEmpty()) addTransactionsSection(document, it) }
            data.locations?.let { if (it.isNotEmpty()) addLocationsSection(document, it) }
            data.bills?.let { if (it.isNotEmpty()) addBillsSection(document, it) }
            data.inventoryItems?.let { if (it.isNotEmpty()) addInventorySection(document, it) }
            data.laborLogs?.let { if (it.isNotEmpty()) addLaborLogsSection(document, it) }
            data.maintenanceLogs?.let { if (it.isNotEmpty()) addMaintenanceLogsSection(document, it) }
            data.analytics?.let { addAnalyticsSection(document, it) }
            
            addFooter(document)
            
            document.close()
            Result.success(file)
        } catch (e: Exception) {
            e.printStackTrace()
            Result.failure(e)
        }
    }
    
    private fun addHeader(document: Document, data: ExportData) {
        document.add(
            Paragraph("FARM DATA REPORT")
                .setFontSize(24f)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(10f)
        )
        
        document.add(
            Paragraph(data.farmName)
                .setFontSize(16f)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(15f)
        )
        
        val infoTable = Table(2)
            .setWidth(UnitValue.createPercentValue(100f))
            .setMarginBottom(20f)
        
        infoTable.addCell(createInfoCell("Generated By:", data.generatedBy))
        infoTable.addCell(createInfoCell("Role:", data.userRole))
        infoTable.addCell(createInfoCell("Export Date:", dateTimeFormat.format(Date(data.exportDate))))
        data.dateRange?.let {
            infoTable.addCell(createInfoCell("Data Range:", it))
        }
        
        document.add(infoTable)
        document.add(Paragraph("\n"))
    }
    
    private fun addMachinesSection(document: Document, machines: List<com.example.agrimanager.data.local.MachineEntity>) {
        addSectionTitle(document, "MACHINES")
        
        val table = Table(floatArrayOf(1f, 3f, 2f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Machine Name"))
        table.addHeaderCell(createHeaderCell("Date Added"))
        
        machines.forEachIndexed { index, machine ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(machine.name))
            table.addCell(createDataCell(dateFormat.format(Date(machine.dateAdded))))
        }
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addFuelLogsSection(document: Document, logs: List<com.example.agrimanager.data.local.FuelLogEntity>) {
        addSectionTitle(document, "FUEL LOGS")
        
        val table = Table(floatArrayOf(1f, 2f, 1.5f, 1.5f, 1.5f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Date"))
        table.addHeaderCell(createHeaderCell("Liters"))
        table.addHeaderCell(createHeaderCell("Rate"))
        table.addHeaderCell(createHeaderCell("Total Cost"))
        
        var totalCost = 0.0
        logs.forEachIndexed { index, log ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(dateFormat.format(Date(log.date))))
            table.addCell(createDataCell("${log.liters} L"))
            table.addCell(createDataCell("Rs. ${log.rate}"))
            table.addCell(createDataCell("Rs. ${log.totalCost}"))
            totalCost += log.totalCost
        }
        
        table.addCell(createTotalCell("TOTAL", 4))
        table.addCell(createTotalCell("Rs. $totalCost", 1))
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addEmployeesSection(document: Document, employees: List<com.example.agrimanager.data.local.EmployeeEntity>) {
        addSectionTitle(document, "EMPLOYEES")
        
        val table = Table(floatArrayOf(1f, 3f, 2f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Name"))
        table.addHeaderCell(createHeaderCell("Base Salary"))
        
        employees.forEachIndexed { index, emp ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(emp.name))
            table.addCell(createDataCell("Rs. ${emp.baseSalary}"))
        }
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addTransactionsSection(document: Document, transactions: List<com.example.agrimanager.data.local.TransactionEntity>) {
        addSectionTitle(document, "SALARY TRANSACTIONS")
        
        val table = Table(floatArrayOf(1f, 2f, 2f, 1.5f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Date"))
        table.addHeaderCell(createHeaderCell("Type"))
        table.addHeaderCell(createHeaderCell("Amount"))
        
        transactions.forEachIndexed { index, trans ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(dateTimeFormat.format(Date(trans.timestamp))))
            table.addCell(createDataCell(if (trans.type == "CREDIT") "Salary Added" else "Advance Given"))
            table.addCell(createDataCell("Rs. ${trans.amount}"))
        }
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addLocationsSection(document: Document, locations: List<com.example.agrimanager.data.local.LocationEntity>) {
        addSectionTitle(document, "LOCATIONS")
        
        val table = Table(floatArrayOf(1f, 4f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Location Name"))
        
        locations.forEachIndexed { index, loc ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(loc.name))
        }
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addBillsSection(document: Document, bills: List<com.example.agrimanager.data.local.BillWithLocation>) {
        addSectionTitle(document, "UTILITY BILLS")
        
        val table = Table(floatArrayOf(1f, 2f, 2f, 1.5f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Location"))
        table.addHeaderCell(createHeaderCell("Month"))
        table.addHeaderCell(createHeaderCell("Amount"))
        
        var totalAmount = 0.0
        bills.forEachIndexed { index, bill ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(bill.locationName))
            table.addCell(createDataCell(bill.bill.billingMonth))
            table.addCell(createDataCell("Rs. ${bill.bill.amount}"))
            totalAmount += bill.bill.amount
        }
        
        table.addCell(createTotalCell("TOTAL", 3))
        table.addCell(createTotalCell("Rs. $totalAmount", 1))
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addInventorySection(document: Document, items: List<com.example.agrimanager.data.local.InventoryItemEntity>) {
        addSectionTitle(document, "INVENTORY ITEMS")
        
        val table = Table(floatArrayOf(1f, 2f, 1.5f, 1.5f, 1.5f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Item Name"))
        table.addHeaderCell(createHeaderCell("Category"))
        table.addHeaderCell(createHeaderCell("Quantity"))
        table.addHeaderCell(createHeaderCell("Unit"))
        
        items.forEachIndexed { index, item ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(item.name))
            table.addCell(createDataCell(item.category))
            table.addCell(createDataCell("${item.currentQuantity}"))
            table.addCell(createDataCell(item.unit))
        }
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addLaborLogsSection(document: Document, logs: List<com.example.agrimanager.data.local.LaborLogWithEmployee>) {
        addSectionTitle(document, "LABOR LOGS")
        
        val table = Table(floatArrayOf(1f, 2f, 2f, 1.5f, 1.5f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Date"))
        table.addHeaderCell(createHeaderCell("Employee"))
        table.addHeaderCell(createHeaderCell("Work Type"))
        table.addHeaderCell(createHeaderCell("Amount"))
        
        var totalAmount = 0.0
        logs.forEachIndexed { index, log ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(dateFormat.format(Date(log.date))))
            table.addCell(createDataCell(log.employeeName))
            table.addCell(createDataCell(log.workType))
            table.addCell(createDataCell("Rs. ${log.totalAmount}"))
            totalAmount += log.totalAmount
        }
        
        table.addCell(createTotalCell("TOTAL", 4))
        table.addCell(createTotalCell("Rs. $totalAmount", 1))
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addMaintenanceLogsSection(document: Document, logs: List<com.example.agrimanager.data.local.MaintenanceLogWithMachine>) {
        addSectionTitle(document, "MAINTENANCE LOGS")
        
        val table = Table(floatArrayOf(1f, 2f, 2f, 2f, 1.5f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("#"))
        table.addHeaderCell(createHeaderCell("Date"))
        table.addHeaderCell(createHeaderCell("Machine"))
        table.addHeaderCell(createHeaderCell("Tag"))
        table.addHeaderCell(createHeaderCell("Cost"))
        
        var totalCost = 0.0
        logs.forEachIndexed { index, log ->
            table.addCell(createDataCell("${index + 1}"))
            table.addCell(createDataCell(dateFormat.format(Date(log.date))))
            table.addCell(createDataCell(log.machineName))
            table.addCell(createDataCell(log.tag))
            table.addCell(createDataCell("Rs. ${log.cost}"))
            totalCost += log.cost
        }
        
        table.addCell(createTotalCell("TOTAL", 4))
        table.addCell(createTotalCell("Rs. $totalCost", 1))
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addAnalyticsSection(document: Document, analytics: com.example.agrimanager.data.local.ExpenseBreakdown) {
        addSectionTitle(document, "EXPENSE ANALYTICS")
        
        document.add(
            Paragraph("Total Expenses: Rs. ${analytics.totalExpenses}")
                .setFontSize(14f)
                .setBold()
                .setMarginBottom(10f)
        )
        
        val table = Table(floatArrayOf(2f, 2f, 1f))
            .setWidth(UnitValue.createPercentValue(100f))
        
        table.addHeaderCell(createHeaderCell("Category"))
        table.addHeaderCell(createHeaderCell("Amount"))
        table.addHeaderCell(createHeaderCell("Percentage"))
        
        analytics.categories.forEach { category ->
            table.addCell(createDataCell(category.name))
            table.addCell(createDataCell("Rs. ${category.amount}"))
            table.addCell(createDataCell("${category.percentage.toInt()}%"))
        }
        
        document.add(table)
        document.add(Paragraph("\n"))
    }
    
    private fun addSectionTitle(document: Document, title: String) {
        document.add(
            Paragraph(title)
                .setFontSize(16f)
                .setBold()
                .setBackgroundColor(DeviceRgb(240, 240, 240))
                .setPadding(5f)
                .setMarginBottom(10f)
        )
    }
    
    private fun createHeaderCell(text: String): Cell {
        return Cell().add(Paragraph(text))
            .setBackgroundColor(DeviceRgb(66, 133, 244))
            .setFontColor(ColorConstants.WHITE)
            .setBold()
            .setTextAlignment(TextAlignment.CENTER)
            .setPadding(5f)
    }
    
    private fun createDataCell(text: String): Cell {
        return Cell().add(Paragraph(text))
            .setPadding(5f)
    }
    
    private fun createTotalCell(text: String, colspan: Int): Cell {
        return Cell(1, colspan).add(Paragraph(text))
            .setBackgroundColor(DeviceRgb(230, 230, 230))
            .setBold()
            .setPadding(5f)
    }
    
    private fun createInfoCell(label: String, value: String): Cell {
        return Cell().add(
            Paragraph("$label $value")
                .setFontSize(10f)
        ).setPadding(3f)
    }
    
    private fun addFooter(document: Document) {
        document.add(
            Paragraph("Generated by AgriManager")
                .setFontSize(8f)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(20f)
        )
    }
}
