package com.example.agrimanager.utils

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Utility class for sharing transaction receipts and data
 * Can be used across all modules (Salary, Inventory, Bills, etc.)
 */
object ShareHelper {
    
    /**
     * Share transaction receipt as text
     */
    fun shareTransactionReceipt(
        context: Context,
        employeeName: String,
        transactionType: String,
        amount: Double,
        date: Long,
        balance: Double? = null
    ) {
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        val formattedDate = dateFormat.format(Date(date))
        
        val receiptText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📄 AgriManager Receipt")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Employee: $employeeName")
            appendLine("Type: $transactionType")
            appendLine("Amount: Rs ${amount.toInt()}")
            appendLine("Date: $formattedDate")
            balance?.let {
                appendLine()
                appendLine("Current Balance: Rs ${it.toInt()}")
            }
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, receiptText, "Transaction Receipt")
    }
    
    /**
     * Share employee ledger summary
     */
    fun shareEmployeeLedger(
        context: Context,
        employeeName: String,
        totalSalary: Double,
        totalAdvances: Double,
        balance: Double,
        transactionCount: Int
    ) {
        val ledgerText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📊 Employee Ledger")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Employee: $employeeName")
            appendLine()
            appendLine("Total Salary Paid: Rs ${totalSalary.toInt()}")
            appendLine("Total Advances: Rs ${totalAdvances.toInt()}")
            appendLine("Current Balance: Rs ${balance.toInt()}")
            appendLine()
            appendLine("Total Transactions: $transactionCount")
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, ledgerText, "Employee Ledger")
    }
    
    /**
     * Share stock transaction receipt
     */
    fun shareStockTransactionReceipt(
        context: Context,
        itemName: String,
        transactionType: String,
        quantity: Double,
        unit: String,
        date: Long,
        currentStock: Double? = null
    ) {
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        val formattedDate = dateFormat.format(Date(date))
        
        val receiptText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📦 Stock Receipt")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Item: $itemName")
            appendLine("Type: $transactionType")
            appendLine("Quantity: ${quantity.toInt()} $unit")
            appendLine("Date: $formattedDate")
            currentStock?.let {
                appendLine()
                appendLine("Current Stock: ${it.toInt()} $unit")
            }
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, receiptText, "Stock Receipt")
    }
    
    /**
     * Share stock report summary
     */
    fun shareStockReport(
        context: Context,
        itemName: String,
        currentStock: Double,
        unit: String,
        totalIn: Double,
        totalOut: Double,
        transactionCount: Int
    ) {
        val reportText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📊 Stock Report")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Item: $itemName")
            appendLine()
            appendLine("Current Stock: ${currentStock.toInt()} $unit")
            appendLine("Total Stock In: ${totalIn.toInt()} $unit")
            appendLine("Total Stock Out: ${totalOut.toInt()} $unit")
            appendLine()
            appendLine("Total Transactions: $transactionCount")
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, reportText, "Stock Report")
    }
    
    /**
     * Share via WhatsApp
     */
    fun shareViaWhatsApp(
        context: Context,
        text: String,
        phoneNumber: String? = null
    ) {
        try {
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                setPackage("com.whatsapp")
                putExtra(Intent.EXTRA_TEXT, text)
                phoneNumber?.let {
                    // Format: country code + number (e.g., 92XXXXXXXXXX)
                    putExtra("jid", "$it@s.whatsapp.net")
                }
            }
            
            if (intent.resolveActivity(context.packageManager) != null) {
                context.startActivity(intent)
            } else {
                // WhatsApp not installed, fallback to regular share
                shareText(context, text, "Share via WhatsApp")
            }
        } catch (e: Exception) {
            // Fallback to regular share
            shareText(context, text, "Share")
        }
    }
    
    /**
     * Share via SMS
     */
    fun shareViaSMS(
        context: Context,
        text: String,
        phoneNumber: String? = null
    ) {
        try {
            val uri = if (phoneNumber != null) {
                Uri.parse("smsto:$phoneNumber")
            } else {
                Uri.parse("smsto:")
            }
            
            val intent = Intent(Intent.ACTION_SENDTO, uri).apply {
                putExtra("sms_body", text)
            }
            
            context.startActivity(intent)
        } catch (e: Exception) {
            // Fallback to regular share
            shareText(context, text, "Share via SMS")
        }
    }
    
    /**
     * Generic text sharing (shows share sheet)
     */
    fun shareText(
        context: Context,
        text: String,
        title: String = "Share"
    ) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, title)
        }
        
        val chooser = Intent.createChooser(intent, title)
        context.startActivity(chooser)
    }
    
    /**
     * Export ledger to CSV file and share
     */
    fun exportAndShareCSV(
        context: Context,
        fileName: String,
        headers: List<String>,
        rows: List<List<String>>
    ) {
        try {
            val file = File(context.cacheDir, "$fileName.csv")
            FileWriter(file).use { writer ->
                // Write headers
                writer.append(headers.joinToString(","))
                writer.append("\n")
                
                // Write rows
                rows.forEach { row ->
                    writer.append(row.joinToString(","))
                    writer.append("\n")
                }
            }
            
            // Share the file
            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
            
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/csv"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            
            context.startActivity(Intent.createChooser(intent, "Export CSV"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    
    /**
     * Generate PDF receipt (placeholder - requires PDF library)
     */
    fun generatePDFReceipt(
        context: Context,
        employeeName: String,
        transactionType: String,
        amount: Double,
        date: Long
    ) {
        // TODO: Implement PDF generation using a library like iText or PDFBox
        // For now, share as text
        shareTransactionReceipt(context, employeeName, transactionType, amount, date)
    }
}
