package com.example.agrimanager.utils

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Utility class for sharing transaction receipts and data
 * Can be used across all modules (Salary, Inventory, Bills, etc.)
 */
object ShareHelper {
    
    /**
     * Share transaction receipt as text
     */
    fun shareTransactionReceipt(
        context: Context,
        employeeName: String,
        transactionType: String,
        amount: Double,
        date: Long,
        balance: Double? = null
    ) {
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        val formattedDate = dateFormat.format(Date(date))
        
        val receiptText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📄 AgriManager Receipt")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Employee: $employeeName")
            appendLine("Type: $transactionType")
            appendLine("Amount: Rs ${amount.toInt()}")
            appendLine("Date: $formattedDate")
            balance?.let {
                appendLine()
                appendLine("Current Balance: Rs ${it.toInt()}")
            }
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, receiptText, "Transaction Receipt")
    }
    
    /**
     * Share employee ledger summary
     */
    fun shareEmployeeLedger(
        context: Context,
        employeeName: String,
        totalSalary: Double,
        totalAdvances: Double,
        balance: Double,
        transactionCount: Int
    ) {
        val ledgerText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📊 Employee Ledger")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Employee: $employeeName")
            appendLine()
            appendLine("Total Salary Paid: Rs ${totalSalary.toInt()}")
            appendLine("Total Advances: Rs ${totalAdvances.toInt()}")
            appendLine("Current Balance: Rs ${balance.toInt()}")
            appendLine()
            appendLine("Total Transactions: $transactionCount")
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, ledgerText, "Employee Ledger")
    }
    
    /**
     * Generate PDF for employee ledger with transaction history
     */
    fun generateEmployeeLedgerPDF(
        context: Context,
        employeeName: String,
        baseSalary: Double,
        totalSalary: Double,
        totalAdvances: Double,
        balance: Double,
        transactions: List<com.example.agrimanager.ui.employee.TransactionWithBalance> = emptyList()
    ) {
        try {
            // Convert TransactionWithBalance to TransactionWithEmployee
            val transactionsWithEmployee = transactions.map { txWithBalance ->
                val tx = txWithBalance.transaction
                com.example.agrimanager.data.models.TransactionWithEmployee(
                    id = tx.id,
                    employeeId = tx.employeeId,
                    employeeName = employeeName,
                    amount = tx.amount,
                    type = tx.type,
                    timestamp = tx.timestamp
                )
            }
            
            // Create ExportData with employee and transactions
            val exportData = com.example.agrimanager.data.models.ExportData(
                farmName = "AgriManager",
                exportDate = System.currentTimeMillis(),
                generatedBy = employeeName,
                userRole = "Employee Ledger",
                dateRange = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date()),
                machines = null,
                fuelLogs = null,
                employees = listOf(
                    com.example.agrimanager.data.local.EmployeeEntity(
                        id = 0,
                        name = employeeName,
                        baseSalary = baseSalary
                    )
                ),
                transactions = transactionsWithEmployee,
                locations = null,
                bills = null,
                inventoryItems = null,
                stockTransactions = null,
                laborLogs = null,
                maintenanceLogs = null,
                dairyLogs = null,
                analytics = null
            )
            
            // Use PdfExportManager to generate PDF
            val pdfExportManager = com.example.agrimanager.utils.PdfExportManager(context)
            val result = pdfExportManager.generatePdf(exportData)
            
            if (result.isSuccess) {
                val file = result.getOrNull()!!
                
                // Share the generated PDF
                val uri = FileProvider.getUriForFile(
                    context,
                    "${context.packageName}.provider",
                    file
                )
                
                val intent = Intent(Intent.ACTION_SEND).apply {
                    type = "application/pdf"
                    putExtra(Intent.EXTRA_STREAM, uri)
                    putExtra(Intent.EXTRA_SUBJECT, "Employee Ledger - $employeeName")
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                
                context.startActivity(Intent.createChooser(intent, "Share Employee Ledger PDF"))
            } else {
                // If PDF generation fails, fallback to text sharing
                Toast.makeText(context, "PDF generation failed, sharing as text", Toast.LENGTH_SHORT).show()
                shareEmployeeLedger(context, employeeName, totalSalary, totalAdvances, balance, transactions.size)
            }
        } catch (e: Exception) {
            e.printStackTrace()
            // Fallback to text sharing on error
            Toast.makeText(context, "Error: ${e.message}", Toast.LENGTH_LONG).show()
            shareEmployeeLedger(context, employeeName, totalSalary, totalAdvances, balance, transactions.size)
        }
    }
    
    /**
     * Share stock transaction receipt with complete details
     */
    fun shareStockTransactionReceipt(
        context: Context,
        itemName: String,
        transactionType: String,
        quantity: Double,
        unit: String,
        date: Long,
        currentStock: Double? = null,
        locationName: String? = null,
        employeeName: String? = null,
        totalCost: Double? = null
    ) {
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        val formattedDate = dateFormat.format(Date(date))
        
        val receiptText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📦 Stock Receipt")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Item: $itemName")
            appendLine("Type: $transactionType")
            appendLine("Quantity: ${quantity.toInt()} $unit")
            appendLine("Date: $formattedDate")
            
            // Add location if available (for stock OUT)
            locationName?.let {
                appendLine()
                appendLine("Location: $it")
            }
            
            // Add employee if available (for stock OUT)
            employeeName?.let {
                appendLine("Used By: $it")
            }
            
            // Add cost if available (for stock IN)
            totalCost?.let {
                if (it > 0) {
                    appendLine()
                    appendLine("Total Cost: Rs ${it.toInt()}")
                }
            }
            
            currentStock?.let {
                appendLine()
                appendLine("Current Stock: ${it.toInt()} $unit")
            }
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, receiptText, "Stock Receipt")
    }
    
    /**
     * Share stock report summary
     */
    fun shareStockReport(
        context: Context,
        itemName: String,
        currentStock: Double,
        unit: String,
        totalIn: Double,
        totalOut: Double,
        transactionCount: Int
    ) {
        val reportText = buildString {
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("📊 Stock Report")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine()
            appendLine("Item: $itemName")
            appendLine()
            appendLine("Current Stock: ${currentStock.toInt()} $unit")
            appendLine("Total Stock In: ${totalIn.toInt()} $unit")
            appendLine("Total Stock Out: ${totalOut.toInt()} $unit")
            appendLine()
            appendLine("Total Transactions: $transactionCount")
            appendLine()
            appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Generated by AgriManager")
        }
        
        shareText(context, reportText, "Stock Report")
    }
    
    /**
     * Generate PDF for stock report with transaction history
     */
    fun generateStockReportPDF(
        context: Context,
        itemName: String,
        currentStock: Double,
        unit: String,
        totalIn: Double,
        totalOut: Double,
        totalCost: Double,
        transactions: List<com.example.agrimanager.ui.inventory.StockTransactionWithBalance> = emptyList()
    ) {
        try {
            // Convert StockTransactionWithBalance to StockTransactionWithItem
            val stockTransactionsWithItem = transactions.map { txWithBalance ->
                val tx = txWithBalance.transaction
                com.example.agrimanager.data.models.StockTransactionWithItem(
                    id = tx.id,
                    itemId = tx.itemId,
                    itemName = itemName,
                    type = tx.type,
                    quantity = tx.quantity,
                    totalCost = tx.totalCost,
                    date = tx.date,
                    locationName = txWithBalance.locationName,
                    employeeName = txWithBalance.employeeName
                )
            }
            
            // Create ExportData with inventory item and transactions
            val exportData = com.example.agrimanager.data.models.ExportData(
                farmName = "AgriManager",
                exportDate = System.currentTimeMillis(),
                generatedBy = itemName,
                userRole = "Stock Report",
                dateRange = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date()),
                machines = null,
                fuelLogs = null,
                employees = null,
                transactions = null,
                locations = null,
                bills = null,
                inventoryItems = listOf(
                    com.example.agrimanager.data.local.InventoryItemEntity(
                        id = 0,
                        name = itemName,
                        category = "Stock",
                        currentQuantity = currentStock,
                        unit = unit
                    )
                ),
                stockTransactions = stockTransactionsWithItem,
                laborLogs = null,
                maintenanceLogs = null,
                dairyLogs = null,
                analytics = null
            )
            
            // Use PdfExportManager to generate PDF
            val pdfExportManager = com.example.agrimanager.utils.PdfExportManager(context)
            val result = pdfExportManager.generatePdf(exportData)
            
            if (result.isSuccess) {
                val file = result.getOrNull()!!
                
                // Share the generated PDF
                val uri = FileProvider.getUriForFile(
                    context,
                    "${context.packageName}.provider",
                    file
                )
                
                val intent = Intent(Intent.ACTION_SEND).apply {
                    type = "application/pdf"
                    putExtra(Intent.EXTRA_STREAM, uri)
                    putExtra(Intent.EXTRA_SUBJECT, "Stock Report - $itemName")
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                
                context.startActivity(Intent.createChooser(intent, "Share Stock Report PDF"))
            } else {
                // If PDF generation fails, fallback to text sharing
                Toast.makeText(context, "PDF generation failed, sharing as text", Toast.LENGTH_SHORT).show()
                shareStockReport(context, itemName, currentStock, unit, totalIn, totalOut, transactions.size)
            }
        } catch (e: Exception) {
            e.printStackTrace()
            // Fallback to text sharing on error
            Toast.makeText(context, "Error: ${e.message}", Toast.LENGTH_LONG).show()
            shareStockReport(context, itemName, currentStock, unit, totalIn, totalOut, transactions.size)
        }
    }
    
    /**
     * Share via WhatsApp
     */
    fun shareViaWhatsApp(
        context: Context,
        text: String,
        phoneNumber: String? = null
    ) {
        try {
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                setPackage("com.whatsapp")
                putExtra(Intent.EXTRA_TEXT, text)
                phoneNumber?.let {
                    // Format: country code + number (e.g., 92XXXXXXXXXX)
                    putExtra("jid", "$it@s.whatsapp.net")
                }
            }
            
            if (intent.resolveActivity(context.packageManager) != null) {
                context.startActivity(intent)
            } else {
                // WhatsApp not installed, fallback to regular share
                shareText(context, text, "Share via WhatsApp")
            }
        } catch (e: Exception) {
            // Fallback to regular share
            shareText(context, text, "Share")
        }
    }
    
    /**
     * Share via SMS
     */
    fun shareViaSMS(
        context: Context,
        text: String,
        phoneNumber: String? = null
    ) {
        try {
            val uri = if (phoneNumber != null) {
                Uri.parse("smsto:$phoneNumber")
            } else {
                Uri.parse("smsto:")
            }
            
            val intent = Intent(Intent.ACTION_SENDTO, uri).apply {
                putExtra("sms_body", text)
            }
            
            context.startActivity(intent)
        } catch (e: Exception) {
            // Fallback to regular share
            shareText(context, text, "Share via SMS")
        }
    }
    
    /**
     * Generic text sharing (shows share sheet)
     */
    fun shareText(
        context: Context,
        text: String,
        title: String = "Share"
    ) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, title)
        }
        
        val chooser = Intent.createChooser(intent, title)
        context.startActivity(chooser)
    }
    
    /**
     * Export ledger to CSV file and share
     */
    fun exportAndShareCSV(
        context: Context,
        fileName: String,
        headers: List<String>,
        rows: List<List<String>>
    ) {
        try {
            val file = File(context.cacheDir, "$fileName.csv")
            FileWriter(file).use { writer ->
                // Write headers
                writer.append(headers.joinToString(","))
                writer.append("\n")
                
                // Write rows
                rows.forEach { row ->
                    writer.append(row.joinToString(","))
                    writer.append("\n")
                }
            }
            
            // Share the file
            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
            
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/csv"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            
            context.startActivity(Intent.createChooser(intent, "Export CSV"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    
    /**
     * Generate PDF receipt for salary transactions using PdfExportManager
     */
    fun generatePDFReceipt(
        context: Context,
        employeeName: String,
        transactionType: String,
        amount: Double,
        date: Long
    ) {
        try {
            // Determine transaction type
            val isCredit = transactionType.contains("Salary", ignoreCase = true) || 
                          transactionType.contains("Payment", ignoreCase = true)
            
            // Create a minimal ExportData with just this transaction
            val exportData = com.example.agrimanager.data.models.ExportData(
                farmName = "AgriManager",
                exportDate = System.currentTimeMillis(),
                generatedBy = employeeName,
                userRole = "Receipt",
                dateRange = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date(date)),
                machines = null,
                fuelLogs = null,
                employees = null,
                transactions = listOf(
                    com.example.agrimanager.data.models.TransactionWithEmployee(
                        id = 0,
                        employeeId = 0,
                        employeeName = employeeName,
                        amount = amount,
                        type = if (isCredit) "CREDIT" else "DEBIT",
                        timestamp = date
                    )
                ),
                locations = null,
                bills = null,
                inventoryItems = null,
                stockTransactions = null,
                laborLogs = null,
                maintenanceLogs = null,
                dairyLogs = null,
                analytics = null
            )
            
            // Use PdfExportManager to generate PDF
            val pdfExportManager = com.example.agrimanager.utils.PdfExportManager(context)
            val result = pdfExportManager.generatePdf(exportData)
            
            if (result.isSuccess) {
                val file = result.getOrNull()!!
                
                // Share the generated PDF
                val uri = FileProvider.getUriForFile(
                    context,
                    "${context.packageName}.provider",
                    file
                )
                
                val intent = Intent(Intent.ACTION_SEND).apply {
                    type = "application/pdf"
                    putExtra(Intent.EXTRA_STREAM, uri)
                    putExtra(Intent.EXTRA_SUBJECT, "$transactionType - $employeeName")
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                
                context.startActivity(Intent.createChooser(intent, "Share Receipt PDF"))
            } else {
                // If PDF generation fails, fallback to text sharing
                shareTransactionReceipt(context, employeeName, transactionType, amount, date)
            }
        } catch (e: Exception) {
            e.printStackTrace()
            // Fallback to text sharing on error
            shareTransactionReceipt(context, employeeName, transactionType, amount, date)
        }
    }
}
